apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.sockshop-staging.abd765f3439fc4583aeb075feb61142e-1926929885.eu-west-1.elb.amazonaws.com
  - carts
  http:
  - route:
    - destination:
        host: carts-canary.sockshop-staging.svc.cluster.local
    - destination:
        host: carts-primary.sockshop-staging.svc.cluster.local
      weight: 100
