apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts-db.sockshop-production.abd765f3439fc4583aeb075feb61142e-1926929885.eu-west-1.elb.amazonaws.com
  - carts-db
  http:
  - route:
    - destination:
        host: carts-db.sockshop-production.svc.cluster.local
